language: node_js
node_js:
  - "0.10"
  - "4"
  - "5"
services:
  - mongodb
env:
  - CLIENT_ID=123
  - CLIENT_SECRET=abc
  - HOST=localhost:5000
  - MONGOLAB_URI=mongodb://localhost/lms_test
  - APP_SECRET=helloworld

 
